### ISSUE TITLE
could not find function "get_report"

### ISSUE THREAD

**Issue by analyzer79** [MangoTheCat/bambooHR#46]
Hello,

I get could not find function "get_report" inside bambooHR package. Unfortunately, when running bambooHR:: there is no option to select get_report. According to the documentation the get_report is supposed to allow to get a bambooHR report through report ID.

Thank you.

Regards,

Ali

**Comment by tbowling87** [comment]
Hi,

Thanks for raising this. It would appear that we have neglected to export that function in the package. As a short term workaround, you could try bambooHR::: (3 colons) to see and use this function, but I will look to make an update to the package where this is corrected and the function is more easily available.

Thanks

Tom

**Comment by tbowling87** [comment]
just re-opening this to relate it to the work required to fix this for a new release

**Comment by tbowling87** [comment]
This issue has been closed in #48 and a new release has been made to CRAN, if you update to version 0.1.1 you should find this function is now exported correctly.
